Basic Scalar, Matrix and Vector Math
NamorvSoftworks/Boxer pull request #8
Opened 2020-08-07 04:02 UTC by RealNeGate

2020-08-20 05:08 UTC, netizen-a requested changes
add a `static_assert` to all new functions in `Mat4x4.h` to showcase their functionality. Make the functions `contexpr` if needed.

2020-08-25 00:16 UTC, netizen-a approved these changes
Looks good the basic math functions can be converted to intrinsics now.

2020-08-25 01:17 UTC, travisvroman commented on src/Boxer/Common.h
> +		printf("Darn! %s\n", (err != nullptr) ? err : "");
Change this to something meaningful. :P

2020-08-25 01:19 UTC, travisvroman requested changes

2020-08-25 01:19 UTC, travisvroman commented on src/Boxer/main.cpp
> +
...Do I want to know why main.cpp is including math? It definitely should not be.

2020-08-26 00:01 UTC, travisvroman approved these changes

2020-08-26 00:01 UTC, merged